{{- define "common.configmap" -}}

{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
data:
    {{- range $key, $value := .Values.configs }}
      {{ $key }}: {{ $value }}
    {{- end }}
{{- end -}}
{{- end -}}