apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
     labels:
       app: users
    spec:
      initContainers:
        - name: run-migrations
          image: ekedani/users-migrations:0.1
          imagePullPolicy: IfNotPresent 
          command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://postgres:whereismymind@users-postgres:5432/users_db?sslmode=disable"
            - name: VERSION
              value: "20221022132417"    
      containers:
        - image: ekedani/users:0.1.2 
          imagePullPolicy: IfNotPresent 
          name: users 
          ports:
            - containerPort: 3000 
          envFrom:
            - configMapRef:
                name: users-config
            - secretRef:
                name: users-secret