apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
     labels:
       app: users
    spec:
      initContainers:
        - name: run-migrations
          image: users-service-migrations:0.1
          command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://postgres:whereismymind@users-postgres:5432/postgres?sslmode=disable"
            - name: VERSION
              value: "20221022132417"    
      containers:
        - image: users:0.2  
          imagePullPolicy: Never 
          name: users 
          ports:
            - containerPort: 3000 
          envFrom:
            - configMapRef:
                name: users-config
            - secretRef:
                name: users-secret