apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
    spec:
      containers:
        - name: users-postgres
          image: postgres:14.1-alpine3.15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: users-postgres-config
            - secretRef:
                name: users-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: userpostgredb
      volumes:
        - name: userpostgredb
          persistentVolumeClaim:
            claimName: users-postgres-volume-claim