image:
  name: ekedani/users
  tag: 0.1.4

migrations:
  image:
    name: ekedani/users-migrations
    tag: 0.1
  config:
    POSTGRESQL_URL: "postgres://postgres:whereismymind@users-postgres:5432/users_db?sslmode=disable"
    VERSION: "20221022132417"

configs:
  DB: users_db
  DB_HOST: users-postgres
  KAFKA_HOST: kafka

secrets:
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "d2hlcmVpc215bWluZA=="

service:
  ports:
    - name: http
      port: 80
      containerPort: 3000

ingress:
  path: /api/users
  port: 80