users-postgres:
  fullnameOverride: users-postgres
  postgresqlDatabase: "users_db"
  postgresqlUsername: "postgres"
  postgresqlPassword: "whereismymind"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data  
posts-postgres:
  fullnameOverride: posts-postgres
  postgresqlDatabase: "posts_db"
  postgresqlUsername: "postgres"
  postgresqlPassword: "postspassword"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data
kafka:
  fullnameOverride: kafka   
  numPartitions: 3
  autoCreateTopicsEnable: false
  provisioning:
    enabled: true
    topics:
      - name: posts.comments
      - name: users
    podAnnotations:
      sidecar.istio.io/inject: "false"