---
imageTag: "7.15.0"
replicas: 1

antiAffinity: "soft"

esJavaOpts: "-Xmx128m -Xms128m"
memory: "1024M"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M