apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
     labels:
       app: comments
    spec:
      initContainers:
        - name: run-migrations
          image: hxnchar/comments-migration:0.1
          imagePullPolicy: IfNotPresent 
          command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://postgres:whereismymind@feed-postgres:5432/postgres?sslmode=disable"
            - name: VERSION
              value: "20221023185401"    
      containers:
        - image: hxnchar/comments:0.1  
          imagePullPolicy: IfNotPresent 
          name: comments 
          ports:
            - containerPort: 3000 
          envFrom:
            - configMapRef:
                name: comments-config
            - secretRef:
                name: comments-secret