apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-posts-postgres
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: run-migrations
        image: ekedani/posts-migrations:0.1.3
        imagePullPolicy: IfNotPresent 
        command: ["migrate", "-path", "/migrations", "-database",  "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
        env:
            - name: POSTGRESQL_URL
              value: "postgres://postgres:postspassword@posts-postgres:5432/posts_db?sslmode=disable"
            - name: VERSION
              value: "20221023185401"
      restartPolicy: OnFailure    